module.exports = {
  apps: [
    {
      name: 'raven-api',
      script: 'dist/apps/api/src/main.js',
      cwd: '/home/ravenai/raven-enterprise-bot/backend',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: '4010' },
      out_file: '/home/ravenai/.pm2/logs/raven-api-out.log',
      error_file: '/home/ravenai/.pm2/logs/raven-api-err.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '512M',
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: 'raven-worker',
      script: 'dist/apps/worker/main.js',
      cwd: '/home/ravenai/raven-enterprise-bot/backend',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production' },
      out_file: '/home/ravenai/.pm2/logs/raven-worker-out.log',
      error_file: '/home/ravenai/.pm2/logs/raven-worker-err.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      restart_delay: 5000,
      max_restarts: 10,
    },
    {
      name: 'raven-dashboard',
      script: 'server.js',
      cwd: '/home/ravenai/raven-enterprise-bot/dashboard/.next/standalone',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: '4011', HOSTNAME: '127.0.0.1' },
      out_file: '/home/ravenai/.pm2/logs/raven-dashboard-out.log',
      error_file: '/home/ravenai/.pm2/logs/raven-dashboard-err.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: 'raven-admin',
      script: 'server.js',
      cwd: '/home/ravenai/raven-enterprise-bot/admin-console/.next/standalone',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: '4012', HOSTNAME: '127.0.0.1' },
      out_file: '/home/ravenai/.pm2/logs/raven-admin-out.log',
      error_file: '/home/ravenai/.pm2/logs/raven-admin-err.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      max_memory_restart: '256M',
      restart_delay: 3000,
      max_restarts: 10,
    },
  ],
}
