CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Migration: 20260305000002_add_extra_config_keys
-- Adds payment sandbox keys, PAYMENT_LIVE_MODE toggle, and email template keys

INSERT INTO "SystemConfig" ("id", "key", "value", "description", "group", "is_secret", "updated_at")
VALUES
  (gen_random_uuid(), 'PAYSTACK_TEST_SECRET_KEY',  NULL,    'Paystack TEST secret key (sk_test_...)',        'payment', true,  NOW()),
  (gen_random_uuid(), 'PAYSTACK_TEST_PUBLIC_KEY',  NULL,    'Paystack TEST public key (pk_test_...)',         'payment', false, NOW()),
  (gen_random_uuid(), 'PAYMENT_LIVE_MODE',         'false', 'Set to true to use live Paystack keys',          'payment', false, NOW()),
  (gen_random_uuid(), 'EMAIL_TEMPLATE_WELCOME',    E'<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;background:#f4f4f4;margin:0;padding:0}.container{max-width:600px;margin:40px auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.1)}.header{background:#4F46E5;padding:32px;text-align:center}.header h1{color:#fff;margin:0;font-size:24px}.body{padding:32px;color:#374151}.footer{background:#F9FAFB;padding:20px 32px;text-align:center;color:#9CA3AF;font-size:12px}</style></head><body><div class="container"><div class="header"><h1>Welcome to {{APP_NAME}}!</h1></div><div class="body"><p>Hi {{USER_NAME}},</p><p>Thank you for joining <strong>{{APP_NAME}}</strong>. Your account is ready.</p><p>Get started by logging in to your dashboard:</p><p style="margin:24px 0"><a href="{{DASHBOARD_URL}}" style="background:#4F46E5;color:#fff;padding:12px 24px;border-radius:6px;text-decoration:none;font-weight:600">Go to Dashboard</a></p><p>If you have any questions, reply to this email — we''re happy to help.</p></div><div class="footer">© {{YEAR}} {{APP_NAME}}. All rights reserved.</div></div></body></html>', 'Welcome email sent to new tenant accounts', 'email_template', false, NOW()),
  (gen_random_uuid(), 'EMAIL_TEMPLATE_PASSWORD_RESET', E'<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;background:#f4f4f4;margin:0;padding:0}.container{max-width:600px;margin:40px auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.1)}.header{background:#DC2626;padding:32px;text-align:center}.header h1{color:#fff;margin:0;font-size:24px}.body{padding:32px;color:#374151}.footer{background:#F9FAFB;padding:20px 32px;text-align:center;color:#9CA3AF;font-size:12px}</style></head><body><div class="container"><div class="header"><h1>Reset Your Password</h1></div><div class="body"><p>Hi {{USER_NAME}},</p><p>We received a request to reset your password. Click the button below to create a new password:</p><p style="margin:24px 0"><a href="{{RESET_URL}}" style="background:#DC2626;color:#fff;padding:12px 24px;border-radius:6px;text-decoration:none;font-weight:600">Reset Password</a></p><p>This link expires in <strong>1 hour</strong>. If you did not request a password reset, you can safely ignore this email.</p></div><div class="footer">© {{YEAR}} {{APP_NAME}}. All rights reserved.</div></div></body></html>', 'Password reset email', 'email_template', false, NOW()),
  (gen_random_uuid(), 'EMAIL_TEMPLATE_INVOICE',    E'<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;background:#f4f4f4;margin:0;padding:0}.container{max-width:600px;margin:40px auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.1)}.header{background:#059669;padding:32px;text-align:center}.header h1{color:#fff;margin:0;font-size:24px}.body{padding:32px;color:#374151}table{width:100%;border-collapse:collapse}th{background:#F3F4F6;padding:12px 16px;text-align:left;font-size:13px;color:#6B7280}td{padding:12px 16px;border-bottom:1px solid #E5E7EB}.total{font-weight:700;font-size:16px}.footer{background:#F9FAFB;padding:20px 32px;text-align:center;color:#9CA3AF;font-size:12px}</style></head><body><div class="container"><div class="header"><h1>Invoice #{{INVOICE_NUMBER}}</h1></div><div class="body"><p>Hi {{USER_NAME}},</p><p>Here is your invoice for <strong>{{BILLING_PERIOD}}</strong>.</p><table><thead><tr><th>Description</th><th>Amount</th></tr></thead><tbody><tr><td>{{PLAN_NAME}} Plan</td><td>{{AMOUNT}}</td></tr><tr><td class="total">Total</td><td class="total">{{AMOUNT}}</td></tr></tbody></table><p style="margin-top:24px">Payment was processed on {{PAYMENT_DATE}} via Paystack.</p></div><div class="footer">© {{YEAR}} {{APP_NAME}}. All rights reserved.</div></div></body></html>', 'Invoice/receipt email after successful payment', 'email_template', false, NOW()),
  (gen_random_uuid(), 'EMAIL_TEMPLATE_SUBSCRIPTION_CONFIRMED', E'<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;background:#f4f4f4;margin:0;padding:0}.container{max-width:600px;margin:40px auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.1)}.header{background:#7C3AED;padding:32px;text-align:center}.header h1{color:#fff;margin:0;font-size:24px}.body{padding:32px;color:#374151}.badge{display:inline-block;background:#EDE9FE;color:#5B21B6;padding:6px 14px;border-radius:20px;font-weight:600;font-size:14px;margin:8px 0}.footer{background:#F9FAFB;padding:20px 32px;text-align:center;color:#9CA3AF;font-size:12px}</style></head><body><div class="container"><div class="header"><h1>Subscription Confirmed 🎉</h1></div><div class="body"><p>Hi {{USER_NAME}},</p><p>Your subscription has been activated:</p><div class="badge">{{PLAN_NAME}}</div><p>You now have access to <strong>{{CONVERSATIONS_LIMIT}}</strong> conversations per month. Your plan renews on <strong>{{RENEWAL_DATE}}</strong>.</p><p style="margin:24px 0"><a href="{{DASHBOARD_URL}}" style="background:#7C3AED;color:#fff;padding:12px 24px;border-radius:6px;text-decoration:none;font-weight:600">Access Dashboard</a></p></div><div class="footer">© {{YEAR}} {{APP_NAME}}. All rights reserved.</div></div></body></html>', 'Sent when a subscription is created or upgraded', 'email_template', false, NOW())
ON CONFLICT ("key") DO NOTHING;
